### ISSUE TITLE
After upgrading onlyoffice app from 9.6.0 to 9.7.0 or 9.8.0, there are a lot of critical error.

### ISSUE THREAD

**Issue by git-ikeda** [nextcloud/documentserver_community#358]
After upgrading onlyoffice app from 9.6.0 to 9.7.0 or 9.8.0, there are a lot of critical error.

ArgumentCountError
Too few arguments to function OCA\Onlyoffice\AppConfig::__construct(), 1 passed in /var/www/html/nextcloud/apps/documentserver_community/lib/AppInfo/Application.php on line 76 and exactly 4 expected
Could not boot documentserver_community: Too few arguments to function OCA\Onlyoffice\AppConfig::__construct(), 1 passed in /var/www/html/nextcloud/apps/documentserver_community/lib/AppInfo/Application.php on line 76 and exactly 4 expected

Nextcloud 30.0.10 with Community Document Server 0.1.20 and PHP 8.3.19 on Ubuntu 22.04.5 LTS

**Comment by chadek** [comment]
Should be fix by now

**Comment by git-ikeda** [comment]
It hasn't been fixed yet.

I have attached reproduction steps.

[Reproduction_steps.pdf](https://github.com/user-attachments/files/19997949/Reproduction_steps.pdf)

**Comment by git-ikeda** [comment]
After upgrading Document Server 0.1.20 to 0.2.0, Everything has been all right.
Thank you very much !!!
